# Generated by Django 5.2.7 on 2025-10-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindowConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('modern', 'Modern'), ('traditional', 'Traditional'), ('cottage', 'Cottage')], default='modern', max_length=20)),
                ('window_color', models.CharField(choices=[('#FFFFFF', 'White'), ('#8B4513', 'Brown'), ('#2C3E50', 'Dark Gray'), ('#000000', 'Black'), ('#D4AF37', 'Gold'), ('#C0C0C0', 'Silver')], default='#FFFFFF', max_length=7)),
                ('window_type', models.CharField(choices=[('standard', 'Standard'), ('bay', 'Bay Window'), ('sliding', 'Sliding'), ('casement', 'Casement'), ('awning', 'Awning'), ('picture', 'Picture')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
